server:
  port: 8082
  tomcat:
      uri-encoding: UTF-8
      max-threads: 1000
      max-connections: 20000
spring:
  application:
  redis:
    host: localhost
    port: 6379
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
logging:
   path: G:/myspac/springboot/nginxtwo/
   file: springbootdemo.log
   level:
     root: INFO;
     com.example.nginxtwo.config: WARN;
   pattern:
     console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
     file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'


